#!/bin/bash

Color_Off='\033[0m' 
BRed="\033[1;31m"         # Red
BGreen="\033[1;32m"       # Green
BYellow="\033[1;33m"      # Yellow
BBlue="\033[1;34m"        # Blue

MSG_FILE=$1
FILE_CONTENT="$(cat $MSG_FILE)"
# Initialize constants here
export REGEX='(breaking: |build: |ci: |chore: |docs: |feat: |fix: |other: |perf: |refactor: |revert: |style: |test: |Merge branch)'
export ERROR_MSG="Commit message format must match regex \"${REGEX}\""
if [[ $FILE_CONTENT =~ $REGEX ]]; then
    printf "${BGreen}Commit Successful!${Color_Off}"
    else
    printf "${BRed}Commit Failed ${BBlue}\"$FILE_CONTENT\"\n"
    printf "${BYellow}$ERROR_MSG\n"

    exit 1
fi

exit 0