#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only)

# Define files that should skip build
SKIP_BUILD_PATHS=("README.md" ".gitlab-ci.yml" "Jenkinsfile.groovy" "git-hooks/" "Dockerfile" "docker-compose.yaml" "kube/")

# Function to check if only skip build files were changed

check_if_only_skip_build_files_changed() {
  for file in $STAGED_FILES; do
    skip=false
    for skip_path in "${SKIP_BUILD_PATHS[@]}"; do
      # If file not in skip list, return false (i.e. need to run build)
      if [[ $file == $skip_path* ]]; then
        skip=true
        break
      fi
    done

    if ! $skip; then
      return 1 # non-skip files were changed
    fi
  done
  return 0 # only skip files were changed
}

if check_if_only_skip_build_files_changed; then
  echo "Build files not changed. Skipping build tasks..."
  exit 0
else
  echo "Build files were changed. Running build tasks..."

  # Using gradle wrapper to ensure project can build, test and check code quality.
  ./gradlew clean build --rerun-tasks

  # store the last exit code in a variable
  RESULT=$?

  # return the exit code
  exit $RESULT
fi
